version: "3"

services:
  app:
    container_name: generative-ai-examples
    build: .
    image: generative-ai-examples:latest
    volumes:
      - ./app:/app
      - ~/.aws:/root/.aws
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 5678:5678
    working_dir: /app
    entrypoint: sleep infinity
